### ISSUE TITLE
Ability to remove files/attachments from messages

### ISSUE THREAD

**Issue by PyICoder** [iDevision/enhanced-discord.py#106]
### Summary

When editing a messaged, files can be added but can't be removed

### What is the feature request for?

discord.ext.commands

### The Problem

So in my program I am sending an image, then replacing it with another something, similar to this:
```py
message = await ctx.send(...,file=discord.File(...))
await message .edit(file=discord.File(...))
```
But realized it keeps the previous image, so I tried:
```py
await message.edit(files=[discord.File(...)])
```
But also realized it just adds a multiple of images/files not replace the first one sent

### The Ideal Solution

Using the `files` parameter in [WebhookMessage](https://enhanced-dpy.readthedocs.io/en/latest/api.html#discord.WebhookMessage) (which is returned from sending a message), it will replace all current files/attachments in the message with the ones included in the list.  Or an separate parameter or method.

**Comment by Gnome-py** [comment]
This is not supported by the API.
https://discord.com/developers/docs/resources/channel#edit-message
