### ISSUE TITLE
Empty string in command.Option description

### ISSUE THREAD

**Issue by jbdoderlein** [iDevision/enhanced-discord.py#107]
### Summary

When you register a command with "" as description in command.Option parameters, the bot start, freeze and don't send any error 

### Reproduction Steps

Create a command with a `commands.Option` with a an empty string as description

### Minimal Reproducible Code

```python
@bot.command()
async def test(ctx, test: str = commands.Option(description="")):
    await ctx.send(f"test : {test}")
```

### Expected Results

Raise an error

### Actual Results

Freeze the bot

### Intents

default

### System Information

- Python v3.9.6-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3661+g96153bb1
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Gnome-py** [comment]
I understand why this is an error, but not why it causes a hang without error. This should give an httpexception on startup.
