### ISSUE TITLE
Slash Command support for CommandGroup where invoke_without_command is True

### ISSUE THREAD

**Issue by dfitzpatrick** [iDevision/enhanced-discord.py#111]
### Summary

Slash Commands missing on Groups where invoke_without_command = True

### Reproduction Steps

Any command group where you pass the kwarg invoke_without_command does not register as a slash command, but only a text command.

### Minimal Reproducible Code

```python
`@commands.group(name='foo', invoke_without_command=True)
async def foo(ctx, bar: str):
     await ctx.send(bar)

@foo.command(name='test')
async def foo_test(ctx, bar: str):
     await ctx.send(bar)
`
```

### Expected Results

/foo "hello"   sends "hello" to the channel.
/foo test "hello" sends "hello to the channel.

### Actual Results

/foo "Hello"   does not send to channel nor register for autocomplete
/foo test "Hello" works as intended.

### Intents

members, guilds, messages

### System Information

- Python v3.8.3-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3664+g2126a24
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by IAmTomahawkx** [comment]
Slash commands do not have this capability. This is a discord limitation.
