### ISSUE TITLE
Version 2.0 is not the default version

### ISSUE THREAD

**Issue by PythonCoderAS** [iDevision/enhanced-discord.py#141]
### Summary

The pypi package does not have any of the improvements mentioned in the changelog.

### Reproduction Steps

N/A

### Minimal Reproducible Code

```python
N/A
```

### Expected Results

The 2.0 version to exist on PyPi, at least in a limited form.

### Actual Results

Version 1.7.3 was installed instead.

### Intents

N/A

### System Information

- Python v3.8.2-final
- discord.py v1.7.3-final
- aiohttp v3.6.3
- system info: Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Chiggy-Playz** [comment]
Version 2.0 is not out on pypi yet. It will be released when the new slash commands implementation is released.

**Comment by GnomedDev** [comment]
Yes, this is the same as normal discord.py, install from git if you want the 2.0 improvements.

**Comment by PythonCoderAS** [comment]
> Yes, this is the same as normal discord.py, install from git if you want the 2.0 improvements.

My problem is that this isn't made clear in the README.

**Comment by iDutchy** [comment]
The contents on pypi do not state anything about 2.0, the readme does mention to install from git. Once it's released to pypi this will be changed to the pypi install. Other than that, sure the readme doesn't include the pypi version isn't 2.0, but it also doesn't state that you must install from there.

**Comment by PythonCoderAS** [comment]
> The contents on pypi do not state anything about 2.0, the readme does mention to install from git. Once it's released to pypi this will be changed to the pypi install. Other than that, sure the readme doesn't include the pypi version isn't 2.0, but it also doesn't state that you must install from there.

The README mentions pypi first. And it states that the git is for the development version, not mentioning that everything past the initial fork is "development".

**Comment by iDutchy** [comment]
My bad, I thought we removed the pypi install. But it technically isn't wrong. enhanced-dpy existed before it became a maintained version of dpy. Before that it was just me messing around with things. That's why it exists on pypi. It is in fact still a development version as there is still work to be done. As soon as those things are finished, and tested without issues, then it'll be released. Until then the git version is still development and pypi is still "stable" just like d.py

**Comment by PythonCoderAS** [comment]
Ah, thanks for the clarification.
