### ISSUE TITLE
PyPi GitHub Repo Discrepancy

### ISSUE THREAD

**Issue by AndrewKahr** [iDevision/enhanced-discord.py#146]
### Summary

The github repo on PyPi points to a fork by iDutchy which is not the same as this git repo and several months out of date.

### Reproduction Steps

Go to the PyPi repo for enhanced-dpy (https://pypi.org/project/enhanced-dpy/) which is the package that is pointed to by the installation instructions.

### Expected Results

N/A

### Actual Results

N/A

### Intents

N/A

### System Information

N/A

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This is more of a question than a bug report. Is the PyPi package out of date/pointing to the right build/repo?

**Comment by IAmTomahawkx** [comment]
Not a bug, 2.0 is still in development.

**Comment by Chiggy-Playz** [comment]
@IAmTomahawkx they mean the project links is messed up. It leads to the wrong repo/

**Comment by IAmTomahawkx** [comment]
Oh I see, that makes sense as it used to be under @iDutchy 's account. Not something we can fix without releasing a new version to pypi afaik, so it's still a wontfix
