### ISSUE TITLE
Clean_prefix problem with /commands

### ISSUE THREAD

**Issue by lvlahraam** [iDevision/enhanced-discord.py#71]
### Summary

clean_prefix returns `@bot's mention` for /commands

### Reproduction Steps

I have `self.context.clean_prefix` in my help command, so i noticed it like that

### Expected Results

Shouldn't it needs to return the main prefix of the bot ? or at least like return `/` ?

### Actual Results

Ok so if someone uses `ctx.clean_prefix` with slash commands
`clean_prefix` will return `@bot's mention` 

### Intents

discord.Intents.all()

### System Information

python bot.py

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by lvlahraam** [comment]
![ss1](https://user-images.githubusercontent.com/79662326/134210610-f153c958-8c93-4741-a4d8-31275a68418e.png)

**Comment by Gnome-py** [comment]
This was fixed by #75 as the prefix is now fixed to `/` instead of the first prefix available (which in your case was the bot mention).
